### ISSUE TITLE
Бесконечные рельсы

### ISSUE THREAD

**Issue by UDQD** [AlexClaw2303/DROP-TABLE-#8]
Дюп рельс существует во многих версиях игры и 1.17.1 не исключение.
Для его реализации нужно построить механизм с картинке ниже (есть несколько вариаций данного механизма)
![image](https://user-images.githubusercontent.com/70804333/134028339-c9d7087b-75bc-4f17-bd27-eb197feaa406.png)
Далее необходимо всего лишь активировать рычаг. После этого механизм запускается и работает циклически выдвигая и задвигая поршень в центре. Происходит это несколько раз в секунду. На каждом такте выдвижения поршня выпадает 4 рельсы в виде предметов, но при этом установленные рельсы остаются на своих местах.
![image](https://user-images.githubusercontent.com/70804333/134029310-924be909-1445-4064-9dbf-fb49ccfcef54.png)

**Comment by mentoster** [comment]
уже есть похожий баг
